db_port: 3306
db_ip: 127.0.0.1
db_database: tmgg-demo-db
db_username: root
db_password: 123456

spring:
  profiles:
    # 注意 必须包含框架的default
    active: default

  application:
    name: 'template'
  jpa:
    show-sql: false

sys:
  cache-dir: /data/cache/tmgg-demo

logging:
  level:
    io.tmgg: info

